package com.example.healthcare.enuns;

public enum Especialidade {
    NUTRICIONISTA,
    FISIOTERAPEUTA,
    CUIDADOR_DE_IDOSOS,
    ENFERMEIRO,
    FARMACEUTICO,
    TECNICO_ENFERMAGEM,
    TECNICO_AMBULANCIA,
    MEDICO_GERIATRICO,
    PEDIATRA,
    CARDIOLOGISTA,
    ORTOPEDISTA,
    TECNICO_RADIOLOGISTA
}
